# apps/public/data.py  – all static data copied from original Cancerlabteste__4_.py
from collections import defaultdict
import urllib.parse

PRIMARY_BLUE = "#4160BA"

PAGES_PUBLIC = [
    ("public:home",        "home"),
    ("public:research",    "research"),
    ("public:publications","publications"),
    ("public:equipment",   "equipments"),
    ("public:people",      "people"),
    ("public:partners",    "partners"),
    ("public:positions",   "open positions"),
    ("public:news",        "news"),
    ("accounts:login",     "Internal Access"),
]

# ─── PEOPLE ────────────────────────────────────────────────────────────────

PEOPLE = [
    {"name": "Fábio Pittella Silva, PhD", "role": "Principal Investigator - Labhead",
     "photo": "Pittella.jpeg",
     "bio": "Head of the Laboratory of Molecular Pathology of Cancer at the University of Brasília. Ph.D in Molecular Pathology from the Human Genome Center, University of Tokyo (2008); M.Sc. in Medical Sciences from the University of Tokyo (2004); B.Sc. in Pharmacy and Biochemistry (Clinical Analysis) from the Federal University of Juiz de Fora (2001). At the University of Tokyo's Human Genome Center, identified and described the genes WDRPUH, TIPUH1, and SMYD3—the first methyltransferase implicated in human carcinogenesis. Professor at the University of Brasília (since 2008), supervising master's, doctoral, and postdoctoral trainees. Associate researcher in liquid biopsy at the Cancer Precision Medicine Center, Japanese Foundation for Cancer Research (JFCR), Tokyo (since 2018). Visiting professor at Memorial Sloan Kettering Cancer Center, New York (2014–2018), working on methyltransferase inhibitors. Expertise in molecular genetics, with focus on epigenetics, protein methyltransferases, liquid biopsy, and molecular targets for cancer diagnosis/therapy.",
     "degrees": [
         "B.Sc. in Pharmacy & Biochemistry, Federal University of Juiz de Fora (1995–2001)",
         "M.Sc. in Medical Sciences, University of Tokyo (2002–2004)",
         "Ph.D. in Molecular Pathology, University of Tokyo (2004–2008)",
         "Postdoctoral Research in Molecular Pathology, Memorial Sloan Kettering Cancer Center (2014–2015)"
     ], "email": "pittella@unb.br", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/4961976945101495", "orcid": "https://orcid.org/0000-0002-9644-7098"},
    {"name": "Andrea Barretto Motoyama, PhD", "role": "Principal Investigator - Labhead",
     "photo": "andrea.jpg",
     "bio": "Head of the Laboratory of Molecular Pathology of Cancer at the University of Brasília. Associate Professor IV in the Department of Pharmacy at the University of Brasília. She earned a BSc in Biological Sciences (UnB, 1997) and a PhD in Biochemistry (University of Basel, 2002). Her PhD explored signal-transduction pathways that drive cellular resistance to targeted anticancer drugs such as trastuzumab. She completed postdoctoral training at The Scripps Research Institute (RNA stability) and the Burnham Institute for Medical Research (cell-adhesion proteins and Rho-family GTPases). Her work spans cell biology, biochemistry, molecular biology, oncology, and pharmacology.",
     "degrees": ["BSc in Biological Sciences, University of Brasília (1997)",
                 "PhD in Biochemistry, University of Basel (2002)",
                 "Postdoctoral Fellow in RNA Stability, The Scripps Research Institute, La Jolla",
                 "Postdoctoral Fellow in Adhesion Proteins & Rho-family GTPases, Burnham Institute for Medical Research, La Jolla"],
     "email": "andreabm@unb.br", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/6229434599232057", "orcid": "https://orcid.org/0000-0002-9280-2638"},
    {"name": "Ana Cristina Moura Gualberto, PhD", "role": "Postdoctoral Fellow",
     "photo": "anagualberto.jpg",
     "bio": "BSc and teaching licensure in Biological Sciences from UFJF, followed by an MSc and PhD in Immunology investigating matrix metalloproteinases in breast cancer, including RNAi-based silencing. She completed a postdoc at UFJF on adipose-tissue exosomes in tumor progression and is currently a postdoctoral fellow at the University of Brasília working with CRISPR/Cas9 genome editing in cancer.",
     "degrees": ["BSc and Teaching Licensure in Biological Sciences, Federal University of Juiz de Fora (2008–2012)",
                 "MSc in Biological Sciences (Immunology), Federal University of Juiz de Fora (2013–2015)",
                 "PhD in Biological Sciences (Immunology), Federal University of Juiz de Fora (2015–2019)",
                 "Postdoctoral Fellow, University of Brasília, CRISPR/Cas9 genome editing in cancer (current)"],
     "email": "", "institution": "Federal University of Juiz de Fora",
     "lattes": "http://lattes.cnpq.br/6338541953564765", "orcid": ""},
    {"name": "Luis Janssen Maia, PhD", "role": "Postdoctoral Fellow",
     "photo": "luisJ.jpg",
     "bio": "Experience in microbiology and molecular biology. Work focuses on high-throughput nucleic-acid sequencing (NGS) using both in-house data and public datasets—to study the diversity and molecular evolution of viruses and bacteria, with applications to molecular studies and liquid biopsy in tumors.",
     "degrees": ["BSc in Biological Sciences, University of Brasília",
                 "MSc in Molecular Biology, University of Brasília",
                 "PhD in Molecular Biology, University of Brasília"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/7167611866112740", "orcid": ""},
    {"name": "Ekaly Ivoneth Porto Apangha, B.Pharm", "role": "Technical assistance",
     "photo": "ekaly.jpg",
     "bio": "Pharmacist graduated from the University of Brasília (UnB); Specialist in Cancer Care from the Escola Superior de Ciências da Saúde (ESCS). Experienced in chemotherapy compounding (antineoplastic handling), Clinical Pharmacy, Oncologic Clinical Pharmacy, Hospital Pharmacy, and Community Pharmacy.",
     "degrees": ["Specialization – Multiprofessional Residency in Cancer Care, ESCS/FEPECS (2018–2020)",
                 "B.Pharm. (Pharmacy), University of Brasília (2011–2016)"],
     "email": "ekaly.apangha@unb.br", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/0622839652506358", "orcid": ""},
    {"name": "André Araújo de Medeiros Silva, MD", "role": "Coloproctologist & General Surgeon - PhD Student",
     "photo": "Andre.jpg",
     "bio": "Master's graduate and current PhD candidate in Medical Sciences at the University of Brasília, focused on the molecular pathology of colorectal cancer. Holds a Biomedicine degree (UniCEUB, 2017) and a specialization in Imaging from Hospital Israelita Albert Einstein (2019).",
     "degrees": ["PhD Candidate in Medical Sciences, University of Brasília (2024–present)",
                 "MSc in Medical Sciences, University of Brasília (2021–2023)",
                 "MD, Escola Bahiana de Medicina e Saúde Pública (1999–2004)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/6330213791982657", "orcid": "https://orcid.org/0000-0002-3691-3739"},
    {"name": "Flávio de Alencar Teles Barreto, MSc", "role": "PhD Student",
     "photo": "flavio.jpg",
     "bio": "Master's graduate and current PhD candidate in Medical Sciences at the University of Brasília, focused on the molecular pathology of colorectal cancer. Holds a Biomedicine degree (UniCEUB, 2017) and a specialization in Imaging from Hospital Israelita Albert Einstein (2019).",
     "degrees": ["BSc in Biomedicine, Centro Universitário de Brasília (2017)",
                 "Postgraduate Specialization in Imaging, Hospital Israelita Albert Einstein (2019)",
                 "MSc in Medical Sciences, University of Brasília",
                 "PhD Candidate in Medical Sciences, University of Brasília"],
     "email": "flavioalencarbarreto92@gmail.com", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/7778492502300819", "orcid": ""},
    {"name": "Brunna Letícia Oliveira Santana, MSc", "role": "PhD Student",
     "photo": "bru.jpg",
     "bio": "Biologist with an MSc in Medical Sciences focused on cancer epigenetics, now a PhD candidate at the University of Brasília investigating lysine methyltransferase knockouts to identify molecular and therapeutic biomarkers for acute lymphoblastic leukemia.",
     "degrees": ["BSc in Biological Sciences, Universidade Paulista – Brasília (2019)",
                 "MSc in Medical Sciences (Cancer Epigenetics), University of Brasília (2022–2024)",
                 "PhD Candidate in Medical Sciences, University of Brasília"],
     "email": "brunna.los@hotmail.com", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/5131211187661647", "orcid": "https://orcid.org/0000-0003-4402-8358"},
    {"name": "Matheus de Oliveira Andrade, MD", "role": "Clinical Oncologist - PhD Student",
     "photo": "matheusmd.jpg",
     "bio": "MD graduated from the University of Brasília (UnB). Fellowship in Internal Medicine at HCFMRP-USP and in Medical Oncology at ICESP-FMUSP. Currently a clinical oncologist at Rede Américas in Brasília and a PhD candidate at the University of Brasília, focusing on liquid biopsy in colorectal cancer.",
     "degrees": ["PhD Candidate in Medical Sciences, University of Brasília (2025–present)",
                 "Medical Residency in Medical Oncology, ICESP – FMUSP (2022–2025)",
                 "MD, University of Brasília (2011–2018)"],
     "email": "matheusandradeoncologia@gmail.com", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/3451033370311538", "orcid": "https://orcid.org/0000-0001-8922-2715"},
    {"name": "Mayra Veloso Ayrimoraes Soares, MD", "role": "Radiologist - PhD Student",
     "photo": "mayramd.jpg",
     "bio": "MD graduated from the University of Brasília (UnB, 1999). Radiologist at Hospital Sírio-Libanês (Brasília-DF) and at Exame/DASA-DF. Currently a PhD candidate in Medical Sciences at the University of Brasília.",
     "degrees": ["PhD Candidate in Medical Sciences, University of Brasília (2022–present)",
                 "Medical Residency in Radiology and Diagnostic Imaging, Hospital de Base do Distrito Federal (2001–2003)",
                 "MD, University of Brasília (1993–1999)"],
     "email": "mayra.veloso@unb.br", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/4358326060572502", "orcid": "https://orcid.org/0000-0003-0796-5123"},
    {"name": "Ísis de Araujo Oliveira Nakashoji, MSc", "role": "PhD Student",
     "photo": "isi.jpg",
     "bio": "Holds a B.Sc. in Pharmacy (University of Brasília, 2018), a Specialization in Clinical Analysis and an M.Sc. in Medical Sciences (University of Brasília, 2021). Currently a PhD candidate in Medical Sciences at the University of Brasília.",
     "degrees": ["PhD Candidate in Medical Sciences, University of Brasília (2021–present)",
                 "M.Sc. in Medical Sciences, University of Brasília (2019–2021)",
                 "B.Sc. in Pharmacy, University of Brasília (2014–2018)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/1743833485792512", "orcid": "https://orcid.org/0000-0002-9303-1169"},
    {"name": "Mariana Braccialli de Loyola, MSc", "role": "PhD Student",
     "photo": "Mari.jpg",
     "bio": "Pharmacist graduated from the University of Brasília (UnB). PhD candidate in the Graduate Program in Medical Sciences at the University of Brasília, under the supervision of Prof. Dr. Fabio Pittella. Developing the project: Functional Evaluation of PSMA in Advanced Prostate Cancer Using CRISPR/Cas9 Models.",
     "degrees": ["Master's in Medical Sciences, University of Brasília (2025)",
                 "B.Pharm. (Pharmacy), University of Brasília (2017–2023)"],
     "email": "maribraccialli@gmail.com", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/4480047944308175", "orcid": "https://orcid.org/0000-0002-7816-764X"},
    {"name": "Lara De Souza Moreno, MD", "role": "Radiologist - PhD Student",
     "photo": "lara.jpg",
     "bio": "Holds a medical degree from the Catholic University of Brasília (2020). Residency in Radiology and Diagnostic Imaging at the University Hospital of Brasília (2025). Master's in Medical Sciences from the University of Brasília (2024).",
     "degrees": ["Master's Candidate in Medical Sciences, University of Brasília (2024–2026)",
                 "Medical Residency in Radiology and Diagnostic Imaging, University Hospital of Brasília / Ebserh (2022–2025)",
                 "M.D., Catholic University of Brasília (2014–2020)"],
     "email": "larasmoreno@gmail.com", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/4568437840946460", "orcid": "https://orcid.org/0009-0002-3390-4551"},
    {"name": "Debora Rodrigues Silveira, B.Pharm", "role": "MSc Student",
     "photo": "dbr.jpg",
     "bio": "Bachelor in Pharmaceutical Sciences from the University of Brasília (UnB), with experience in clinical research and cancer molecular genetics.",
     "degrees": ["M.Sc. Candidate in Medical Sciences, University of Brasília (2025–present)",
                 "B.Sc. in Pharmaceutical Sciences, University of Brasília (2018–2024)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/5490962025847708", "orcid": ""},
    {"name": "Wladimir Fernandes Bezerra, MD", "role": "Surgical Oncologist - Master's Student",
     "photo": "wl.jpg",
     "bio": "MD graduated from the University of Brasília (UnB). Residency in General Surgery (ESCS) and in Surgical Oncology at the Hospital de Base do Distrito Federal (HBDF). Pursuing a Master's degree in Molecular Pathology at the University of Brasília, focused on perioperative cfDNA dynamics in gastric cancer surgery.",
     "degrees": ["MD, University of Brasília (UnB)",
                 "Residency in General Surgery, Escola Superior de Ciências da Saúde (ESCS)",
                 "Residency in Surgical Oncology, Hospital de Base do Distrito Federal (HBDF)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/9132471167946295", "orcid": ""},
    {"name": "Daniel dos Santos Ramos, B.Pharm", "role": "MSc Student",
     "photo": "daniel.jpg",
     "bio": "Holds a B.Pharm. from the Euro-American Institute of Education, Science and Technology (2013) and a postgraduate specialization in Forensic Sciences from UniLS. Currently a Master's student in the Graduate Program in Nanoscience and Nanobiotechnology at the University of Brasília (UnB).",
     "degrees": ["Master's Candidate in Nanoscience and Nanobiotechnology, University of Brasília (2025–present)",
                 "Specialization in Forensic Sciences, UniLS (2016–2017)",
                 "B.Pharm. (Pharmacy), Euro-American Institute of Education, Science and Technology – EUROAM (2009–2013)"],
     "email": "daniel.ramos@unb.br", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/4153360465428627", "orcid": ""},
    {"name": "Yasmin Albuquerque", "role": "Undergraduate Student",
     "photo": "yas.jpg",
     "bio": "Undergraduate student in Biological Sciences (B.Sc.) at the University of Brasília (since 2022). Has experience in Molecular Biology with a focus on diagnostics, including RNA extraction, RT-PCR, and PCR for Plant Virology.",
     "degrees": ["B.Sc. Candidate in Biological Sciences, University of Brasília (2022–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/2305511706458935", "orcid": ""},
    {"name": "Sofia Arrais Haidar", "role": "Undergraduate Student",
     "photo": "sofia2.jpg",
     "bio": "Fourth-year medical student at the University of Brasília (UnB). Participates in academic leagues: Family and Community Medicine (LAMEF-UnB), Cardiology (LACor-UnB), Surgery (LAC-UnB), Hematology (LAHem-UnB), and Neurology (Neuroliga-UnB).",
     "degrees": ["M.D. student, University of Brasília (2021–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/2664347077103484", "orcid": ""},
    {"name": "Priscila de Medeiros Vergara", "role": "Undergraduate Student",
     "photo": "pri.jpg",
     "bio": "Pharmacy student at the University of Brasília (UnB) (2022–present). Conducts research in microbiology at the Enzymology Laboratory of UnB, working with microorganism cultivation, DNA extraction, and analysis of experimental results.",
     "degrees": ["B.Sc. student in Pharmacy, University of Brasília (2022–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/9595288580014037", "orcid": ""},
    {"name": "Alvaro Reis de Oliveira Queiroz", "role": "Undergraduate Student",
     "photo": "mtl.jpeg",
     "bio": "Bachelor's student in Pharmacy at the University of Brasília (UnB). Experienced with coordination chemistry and applications to biological systems. Working with the generation of stable Cas9-EGFP cancer cell lines, using the Tet-On system.",
     "degrees": ["B.Sc. student in Pharmacy, University of Brasília (2019–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/1126659468006228", "orcid": ""},
    {"name": "Gabriel da Silva Macêdo", "role": "Undergraduate Student",
     "photo": "gabrielft.jpg",
     "bio": "Undergraduate student in Pharmacy at the University of Brasília (UnB), currently in the 6th semester. Interested in research in the fields of molecular biology and genetics.",
     "degrees": ["B.Sc. student in Pharmacy, University of Brasília (2019–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/0351410051448545", "orcid": ""},
    {"name": "Augusto Silva Alves", "role": "Undergraduate Student",
     "photo": "ab.jpg",
     "bio": "Medical student at the University of Brasília (UnB), Brazil. Scientific initiation scholarship holder at UnB.",
     "degrees": ["MD Candidate (Medicine), University of Brasília (2022–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/1220931705760601", "orcid": "https://orcid.org/0009-0005-6099-3889"},
    {"name": "Ângelo Antônio Silva Lima", "role": "Undergraduate Student",
     "photo": "as.jpg",
     "bio": "Medical student at the University of Brasília (UnB), Brazil.",
     "degrees": ["MD Candidate (Medicine), University of Brasília (2022–present)"],
     "email": "", "institution": "University of Brasília",
     "lattes": "http://lattes.cnpq.br/8940572165307881", "orcid": ""},
]

ALUMINI = [
    {"name": "André Victor Castelo de Araujo Oliveira", "lattes": "", "year": "2024", "activity": "Postdoctoral Fellows"},
    {"name": "Ana Cristina Moura Gualberto", "lattes": "http://lattes.cnpq.br/6338541953564765", "year": "2024", "activity": "Postdoctoral Fellows"},
    {"name": "Cíntia Nogueira Hollanda", "lattes": "http://lattes.cnpq.br/4163677223230109", "year": "2024", "activity": "Ph.D."},
    {"name": "André Araújo de Medeiros Silva", "lattes": "http://lattes.cnpq.br/6330213791982657", "year": "2023", "activity": "Ph.D."},
    {"name": "Larissa Fernanda Campos Moreira da Silva", "lattes": "http://lattes.cnpq.br/2380982097052834", "year": "2022", "activity": "Ph.D."},
    {"name": "Mayra Veloso Ayrimoraes Soares", "lattes": "http://lattes.cnpq.br/4358326060572502", "year": "2022", "activity": "Ph.D."},
    {"name": "Ísis de Araujo Oliveira Nakashoji", "lattes": "http://lattes.cnpq.br/1743833485792512", "year": "2021", "activity": "M.Sc."},
    {"name": "Tales Henrique Andrade Mota", "lattes": "http://lattes.cnpq.br/2693085695476965", "year": "2020", "activity": "M.Sc."},
    {"name": "Daniella Alves Rabello", "lattes": "http://lattes.cnpq.br/7063424459226026", "year": "2016", "activity": "M.Sc."},
    {"name": "Luís Augusto Muniz Telles", "lattes": "http://lattes.cnpq.br/1987858702905034", "year": "", "activity": "PIBIC"},
    {"name": "Mariana Braccialli de Loyola", "lattes": "http://lattes.cnpq.br/4480047944308175", "year": "", "activity": "PIBIC"},
    {"name": "Cíntia Nogueira Hollanda", "lattes": "http://lattes.cnpq.br/4163677223230109", "year": "", "activity": "PIBIC"},
    {"name": "Sophia Alves da Costa Pereira", "lattes": "http://lattes.cnpq.br/7674938627453757", "year": "2025", "activity": "PIBIC"},
]

# ─── PUBLICATIONS ───────────────────────────────────────────────────────────

PUBLICATIONS = [
    {"authors": "Lopes, M. A.; Cordeiro, M. E. R.; Barreto, F. A. T.; Moreno, L. S.; Silva, A. A. M.; Loyola, M. B.; Soares, M. V. A.; Sousa, J. B.; Pittella-Silva, F.", "title": "Assessment of cfDNA release dynamics during colorectal cancer surgery", "journal": "Oncotarget", "year": 2025},
    {"authors": "Hollanda, C. N.; Gualberto, A. C. M.; Motoyama, A. B.; Pittella-Silva, F.", "title": "Advancing Leukemia Management Through Liquid Biopsy: Insights into Biomarkers and Clinical Utility", "journal": "Cancers", "year": 2025},
    {"authors": "Olivera Santana, B. L.; De Loyola, M. B.; Gualberto, A. C. M.; Pittella-Silva, F.", "title": "Genetic Alterations of SMYD4 in Solid Tumors Using Integrative Multi-Platform Analysis", "journal": "International Journal of Molecular Sciences", "year": 2024},
    {"authors": "Gatto, C. C.; Cavalcante, C. de Q. O.; Lima, F. C.; Nascimento, É. C. M.; Martins, J. B. L.; Santana, B. L. O.; Gualberto, A. C. M.; Pittella-Silva, F.", "title": "Structural Design, Anticancer Evaluation, and Molecular Docking of Newly Synthesized Ni(II) Complexes with ONS-Donor Dithiocarbazate Ligands", "journal": "Molecules", "year": 2024},
    {"authors": "Silva-Carvalho, A. É.; Féliu-Braga, L. D. C.; Bogéa, G. M. R.; de Assis, A. J. B.; Pittella-Silva, F.; Saldanha-Araujo, F.", "title": "GLP and G9a histone methyltransferases as potential therapeutic targets for lymphoid neoplasms", "journal": "Cancer Cell International", "year": 2024},
    {"authors": "Zhu, Y.; Pittella-Silva, F.; Wang, Y.; Wang, T.; Long, F.", "title": "Editorial: Epigenetic Regulation and Therapy Resistance in Cancer", "journal": "Frontiers in Pharmacology", "year": 2023},
    {"authors": "Cavalcante, C. de Q. O.; da Mota, T. H. A.; de Oliveira, D. M.; Nascimento, É. C. M.; Martins, J. B. L.; Pittella-Silva, F.; Gatto, C. C.", "title": "Dithiocarbazate ligands and their Ni(II) complexes with potential biological activity: Structural, antitumor and molecular docking study", "journal": "Frontiers in Molecular Biosciences", "year": 2023},
    {"authors": "Mota, T. H. A.; Carmargo, R.; Biojone, E. R.; Guimarães, A. F. R.; Pittella-Silva, F.; Oliveira, D. M.", "title": "The Relevance of Telomerase and Telomere-Associated Proteins in B-Acute Lymphoblastic Leukemia", "journal": "Genes", "year": 2023},
    {"authors": "Machado, C. M. L.; Skubal, M.; Haedicke, K.; Silva, F. P.; Stater, E. P.; Silva, T. L. A. O.; Costa, É. T.; Masotti, C.; Otake, A. H.; Andrade, L. N. S.; et al.", "title": "Membrane-derived particles shed by PSMA-positive cells function as pro-angiogenic stimuli in tumors", "journal": "Journal of Controlled Release", "year": 2023},
    {"authors": "Assis, A. J.; Santana, B.; Gualberto, A. C. M.; Silva, F. P.; Pittella-Silva, F.", "title": "Therapeutic applications of CRISPR/Cas9 mediated targeted gene editing in acute lymphoblastic leukemia: current perspectives, future challenges, and clinical implications", "journal": "Frontiers in Pharmacology", "year": 2023},
    {"authors": "Pittella-Silva, F.", "title": "Targeting DNA Methylation as an Epigenetic Leukocyte Counting Tool", "journal": "Clinical Chemistry", "year": 2022},
    {"authors": "Watanabe, K.; Nakamura, T.; Kimura, Y.; Motoya, M.; Kojima, S.; Kuraya, T.; …; Pittella-Silva, F.; Nakamura, Y.; Low, A. S.", "title": "Tumor-informed approach improved ctDNA detection rate in resected pancreatic cancer", "journal": "International Journal of Molecular Sciences", "year": 2022},
    {"authors": "Silva, F. P.; Kimura, Y.; Low, S.-K.; Nakamura, Y.; Motoya, M.", "title": "Amplification of mutant in a patient with advanced metastatic pancreatic adenocarcinoma detected by liquid biopsy: A case report", "journal": "Molecular and Clinical Oncology", "year": 2021},
    {"authors": "Pittella-Silva, F.; Chin, Y. M.; Chan, H. T.; Nagayama, S.; Miyauchi, E.; Low, S.-K.; Nakamura, Y.", "title": "Plasma or Serum: Which Is Preferable for Mutation Detection in Liquid Biopsy?", "journal": "Clinical Chemistry", "year": 2020},
    {"authors": "Doralina do Amaral Rabello Carolina Amaro de Moura Rosangela Vieira de Andrade Andrea Barretto Motoyama Fabio Pittella Silva", "title": "Altered expression of MLL methyltransferase family genes in breast cancer)", "journal": "International Journal of Oncology", "year": 2013, "url": "https://www.spandidos-publications.com/10.3892/ijo.2013.1981", "doi": "10.3892/ijo.2013.1981"},
    {"authors": "Luis Henrique Toshihiro Sakamoto a c d, Rosangela Vieira de Andrade b, Maria Sueli Soares Felipe b c, Andrea Barretto Motoyama, Fabio Pittella Silva", "title": "SMYD2 is highly expressed in pediatric acute lymphoblastic leukemia and constitutes a bad prognostic factor", "journal": "", "year": 2014, "url": "https://www.sciencedirect.com/science/article/pii/S0145212614000319?via%3Dihub"},
    {"authors": "Fabiana Pirani Carneiro Maria Imaculada Muniz-Junqueira Fabio Pittella-Silva Marcos de Vasconcelos Carneiro Gustavo Henrique Soares Takano Leonora Maciel de Sousa Vianna Luciano Barbosa De Andrade Tercia Maria Mendes Lousa De Castro Isabela Peres Tatiana Karla Dos Santos Borges Vânia Moraes Ferreira Andrea Barretto Motoyama", "title": "A panel of markers for identification of malignant and non-malignant cells in culture from effusions", "journal": "Oncology Reports", "year": 2017, "url": "https://www.spandidos-publications.com/10.3892/or.2017.6022", "doi": "10.3892/or.2017.6022"},
    {"authors": "Fabiana Pirani Carneiro, Andersen Charles Darós, Adriana Cysneiro Milhomem Darós, Tércia Maria Mendes Lousa de Castro, Marcos de Vasconcelos Carneiro, Cecília Ramos Fidelis, Mariane Vieira Vilioni, Michelle Egídio da Costa Matsunaga, Jéssica Meneses Othon Sidou, Mariana Anaue Lozi Dias Chaves, Lívia Custódio Pereira, Ceres Nunes de Resende, ", "title": "Cervical Cytology of Samples with Ureaplasma urealyticum, Ureaplasma parvum, Chlamydia trachomatis, Trichomonas vaginalis, Mycoplasma hominis, and Neisseria gonorrhoeae Detected by Multiplex PCR", "journal": "Mediators of Inflammation", "year": 2020, "url": "https://onlinelibrary.wiley.com/doi/10.1155/2020/7045217", "doi": "10.1155/2020/7045217"},
    {"authors": "MOTA, TALES H. A.; GUIMARAES, A. F. R.; CARVALHO, A. E. S.; SALDANHA-ARAUJO, F.; LOPES, G. P. F.; PITTELLA-SILVA, F.; RAMOS, D. A.; OLIVEIRA, D. M.", "title": "Effects of in vitro short- and long-term treatment with telomerase inhibitor in U-251 glioma cells", "journal": "Tumor Biology", "year": 2021, "url": "https://doi.org/10.3233/TUB-211515", "doi": "10.3233/TUB-211515"},
    {"authors": "PITTELLA-SILVA, F.; MOTOYA, M.; KIMURA, Y.; NAKAMURA, T.; LOW, S.-K.; NAKAMURA, Y.", "title": "Assessment of mutation burden after clinical intervention in PDAC and BTC via profiling circulating tumor DNA (ctDNA)", "journal": "Journal of Clinical Oncology", "year": 2020, "url": "https://doi.org/10.1200/JCO.2020.38.15_suppl.e15529", "doi": "10.1200/JCO.2020.38.15_suppl.e15529"},
    {"authors": "CHEN, S.; WIEWIORA, R. P.; MENG, F.; BABAULT, N.; MA, A.; YU, W.; QIAN, K.; HU, H.; ZOU, H.; WANG, J.; FAN, S.; BLUM, G.; PITTELLA-SILVA, F.; BEAUCHAMP, K. A.; TEMPEL, W.; JIANG, H.; CHEN, K.; SKENE, R. J.; ZHENG, Y. G.; BROWN, P. J.; et al.", "title": "The dynamic conformational landscape of the protein methyltransferase SETD8", "journal": "eLife", "year": 2019, "url": "https://doi.org/10.7554/eLife.45403", "doi": "10.7554/eLife.45403"},
    {"authors": "MORAIS, K. S.; ARCANJO, D. S.; LOPES, G. P. F.; SILVA, G. G.; MOTA, T. H. A.; GABRIEL, T. R.; RABELLO RAMOS, D. A.; PITTELLA-SILVA, F.; OLIVEIRA, D. M.", "title": "Long-term in vitro treatment with telomerase inhibitor MST-312 induces resistance by selecting long telomeres cells", "journal": "Cell Biochemistry and Function", "year": 2019, "url": "https://doi.org/10.1002/cbf.3398", "doi": "10.1002/cbf.3398"},
    {"authors": "ALVES-SILVA, J. C.; DE CARVALHO, J. L.; RABELLO, D. A.; SEREJO, T. R. T.; REGO, E. M.; NEVES, F. A. R.; LUCENA-ARAUJO, A. R.; PITTELLA-SILVA, F.; SALDANHA-ARAUJO, F.", "title": "GLP overexpression is associated with poor prognosis in Chronic Lymphocytic Leukemia and its inhibition induces leukemic cell death", "journal": "Investigational New Drugs", "year": 2018, "url": "https://doi.org/10.1007/s10637-018-0613-x", "doi": "10.1007/s10637-018-0613-x"},
    {"authors": "RABELLO, D. A.; FERREIRA, V. D. S.; BERZOTI-COELHO, M. G.; BURIN, S. M.; MAGRO, C. L.; CACEMIRO, M. C.; SIMÕES, B. P.; SALDANHA-ARAUJO, F.; DE CASTRO, F. A.; PITTELLA-SILVA, F.", "title": "MLL2/KMT2D and MLL3/KMT2C expression correlates with disease progression and response to imatinib mesylate in chronic myeloid leukemia", "journal": "Cancer Cell International", "year": 2018, "url": "https://doi.org/10.1186/s12935-018-0523-1", "doi": "10.1186/s12935-018-0523-1"},
    {"authors": "CARVALHO ALVES-SILVA, J.; RABELLO, D. A.; BRAVO, M. O.; LUCENA-ARAUJO, A. R.; DE OLIVEIRA, D. M.; DE OLIVEIRA, F. M.; REGO, E. M.; PITTELLA-SILVA, F.; SALDANHA-ARAUJO, F.", "title": "Aberrant levels of SUV39H1 and SUV39H2 methyltransferase are associated with genomic instability in chronic lymphocytic leukemia", "journal": "Environmental and Molecular Mutagenesis", "year": 2017, "url": "https://doi.org/10.1002/em.22128", "doi": "10.1002/em.22128"},
    {"authors": "COLAÇO, C. S.; DE MATOS, A. R.; ESTRÊLA, M. S.; ROCHA-JÚNIOR, M. C.; OTAGUIRI, K. K.; RODRIGUES, E. S.; TAKAYANAGUI, O. M.; COVAS, D. T.; KASHIMA, S.; PITTELLA SILVA, F.; HADDAD, R.", "title": "Downregulation of histone methyltransferase EHMT2 in CD4+ T-cells may protect HTLV-1-infected individuals against HAM/TSP development", "journal": "Archives of Virology", "year": 2017, "url": "https://doi.org/10.1007/s00705-017-3428-8", "doi": "10.1007/s00705-017-3428-8"},
    {"authors": "MORAIS, K. S.; GUIMARÃES, A. F. R.; RAMOS, D. A. R.; PITTELLA-SILVA, F.; DE OLIVEIRA, D. M.", "title": "Long-term exposure to MST-312 leads to telomerase reverse transcriptase overexpression in MCF-7 breast cancer cells", "journal": "Anti-Cancer Drugs", "year": 2017, "url": "https://doi.org/10.1097/CAD.0000000000000508", "doi": "10.1097/CAD.0000000000000508"},
    {"authors": "BUTLER, K. V.; MA, A.; YU, W.; LI, F.; TEMPEL, W.; BABAULT, N.; PITTELLA-SILVA, F.; SHAO, J.; WANG, J.; LUO, M.; VEDADI, M.; BROWN, P. J.; ARROWSMITH, C. H.; JIN, J.", "title": "Structure-Based Design of a Covalent Inhibitor of the SET Domain-Containing Protein 8 (SETD8) Lysine Methyltransferase", "journal": "Journal of Medicinal Chemistry", "year": 2016, "url": "https://doi.org/10.1021/acs.jmedchem.6b01244", "doi": "10.1021/acs.jmedchem.6b01244"},
    {"authors": "OLIVEIRA-SANTOS, W.; RABELLO, D. A.; LUCENA-ARAUJO, A. R.; OLIVEIRA, F. M.; REGO, E. M.; PITTELLA-SILVA, F.; SALDANHA-ARAUJO, F.", "title": "Residual expression of SMYD2 and SMYD3 is associated with the acquisition of complex karyotype in chronic lymphocytic leukemia", "journal": "Tumor Biology", "year": 2016, "url": "https://doi.org/10.1007/s13277-016-4846-z", "doi": "10.1007/s13277-016-4846-z"},
    {"authors": "DE OLIVEIRA, D. M.; LIMA, R. M. F.; CLARENCIO, J.; VELOZO, E. S.; DE AMORIM, I. A.; MOTA, T. H. A.; COSTA, S. L.; PITTELLA-SILVA, F.; EL-BACHÁ, R. D. S.", "title": "The classical photoactivated drug 8-methoxypsoralen and related compounds are effective without UV light irradiation against glioma cells", "journal": "Neurochemistry International", "year": 2016, "url": "https://doi.org/10.1016/j.neuint.2016.06.004", "doi": "10.1016/j.neuint.2016.06.004"},
    {"authors": "RABELLO, D. A.; LUCENA-ARAUJO, A. R.; ALVES-SILVA, J. C. R.; DA EIRA, V. B. A. S.; DE VASCONCELLOS, M. C. C.; OLIVEIRA, F. M.; REGO, E. M.; SALDANHA-ARAUJO, F.; PITTELLA SILVA, F.", "title": "Overexpression of EZH2 associates with a poor prognosis in chronic lymphocytic leukemia", "journal": "Blood Cells, Molecules and Diseases", "year": 2015, "url": "https://doi.org/10.1016/j.bcmd.2014.07.013", "doi": "10.1016/j.bcmd.2014.07.013"},
    {"authors": "FIGUEIREDO, D.; RABELLO, D.; ZANETTE, D.; SAGGIORO, F.; MAMEDE, R.; ZAGO, M.; DA SILVA, W.; SALDANHA-ARAÚJO, F.; PITTELLA SILVA, F.", "title": "Assessment of MLL methyltransferase gene expression in larynx carcinoma", "journal": "Oncology Reports", "year": 2015, "url": "https://doi.org/10.3892/or.2015.3756", "doi": "10.3892/or.2015.3756"},
    {"authors": "LAFOREST, A.; APARICIO, T.; ZAANAN, A.; PITTELLA-SILVA, F.; DESREBEAUX, A.; LE CORRE, D.; PALLIER, K.; AUST, D.; BLONS, H.; SVRCEK, M.; LAURENT-PUIG, P.", "title": "ERBB2 gene as a potential therapeutic target in small bowel adenocarcinoma", "journal": "European Journal of Cancer", "year": 2014, "url": "https://doi.org/10.1016/j.ejca.2014.04.007", "doi": "10.1016/j.ejca.2014.04.007"},
    {"authors": "FARIA, J. A. Q. A.; CORREA, N. C. R.; ANDRADE, C.; CAMPOS, A. C. A.; ALMEIDA, R. S. S.; GOES, A. M.; GOMES, D. A.; PITTELLA-SILVA, F.", "title": "SETD4 is a Newly Identified Cytosolic and Nuclear Lysine Methyltransferase involved in Breast Cancer Cell Proliferation", "journal": "Journal of Cancer Science & Therapy", "year": 2013, "url": "https://doi.org/10.4172/1948-5956.1000185", "doi": "10.4172/1948-5956.1000185"},
    {"authors": "Davi Trombini Aleixoa, Estael L. C. Cruz-Cazarim, Kezia C. B. Ferreira, Lívia N. Grossi, Wilson R. Braz, Natália P. Silva, Fábio Pittella-Silva, Marina F. Dias, Silvia L. Fialho, Guilherme D. Tavares, Frederico Pittella", "title": "Breakthroughs in the nanoparticle-mediated delivery of siRNA for breast cancer treatment", "journal": "Journal of Cancer Science & Therapy", "year": 2025, "url": "https://doi.org/10.1080/17435889.2025.2567842", "doi": "10.1080/17435889.2025.2567842"},
    {"authors": "MORENO, LARA DE SOUZA ; DA SILVA, TONY ALEXANDRE MEDEIROS ; SOARES, MAYRA VELOSO AYRIMORAES ; DE CARVALHO, JOÃO LUIZ AZEVEDO ; PITTELLA-SILVA, FABIO.", "title": "Machine Learning Radiomics in Computed Tomography for Prediction of Tumor and Nodal Stages in Colorectal Cancer", "journal": "Cancers", "year": 2026, "url": "https://doi.org/10.3390/cancers18030377", "doi": "10.3390/cancers18030377"},
    {"authors": "TELLES, L.A. ; DE LOYOLA, M.B. ; SAKAMOTO, L.T. ; RABELLO, D.D. ; MOTOYAMA, A.B. ; PITTELLA-SILVA, F.", "title": "SETD4 as a marker of disease burden and treatment response in childhood acute lymphoblastic leukemia", "journal": "Oncology Letters", "year": 2026, "url": "https://doi.org/10.3892/ol.2026.15545", "doi": "10.3892/ol.2026.15545"},
    {"authors": "BICALHO, L.O. ; CAVALCANTE, C.Q.O. ; SANTANA, B.L.O. ; GUALBERTO, A.C.M. ; PITTELLA-SILVA, F. ; NASCIMENTO, É.C.M. ; MARTINS, J.B.L. ; GATTO, C.C.", "title": "Central-metal effect on anticancer activity and molecular docking of Co(II), Ni(II), and Zn(II) complexes with isatin-based ligand", "journal": "Journal of Molecular Structure", "year": 2026, "url": "https://doi.org/10.1016/j.molstruc.2026.143066", "doi": "https://doi.org/10.1016/j.molstruc.2026.146386"},
]

# ─── PATENTS ────────────────────────────────────────────────────────────────

def _google_patents_link(q): return f"https://patents.google.com/?q={urllib.parse.quote_plus(q)}"

PATENTS = [
    {"year": 2013, "inventors": "SILVA, F. P. PITTELLA-SILVA, F.; Gomes, A. D.; Lunardi, C. N.; Gomes, D. A.", "title": "Composição antitumoral à base de micro e nanopartículas poliméricas, seu processo de obtenção e suas aplicações", "jurisdiction": "Brazil (INPI)", "number": "BR102013017203", "deposited": "2013-07-04", "url": "https://patents.google.com/?q=BR102013017203"},
    {"year": 2015, "inventors": "LUO, M.; BLUM, G.; SANCHEZ, G. I.; YANG, L.; SILVA, F. P. PITTELLA-SILVA, F.", "title": "Naphthaquinone Methyltransferase Inhibitors and Uses Thereof", "jurisdiction": "WIPO (PCT)", "number": "WO/2015/172076", "deposited": "2015-08-05", "granted": "2015-12-11", "url": "https://patents.google.com/?q=WO2015172076"},
    {"year": 2015, "inventors": "LUO, M.; BLUM, G.; SANCHEZ, G. I.; SILVA, F. P. PITTELLA-SILVA, F.", "title": "Naphthaquinone Methyltransferase Inhibitors and Uses Thereof", "jurisdiction": "Canada (CIPO)", "number": "CA2946609", "deposited": "2015-12-11", "url": "https://patents.google.com/?q=CA2946609"},
    {"year": 2016, "inventors": "LUO, M.; BLUM, G.; SANCHEZ, G. I.; SILVA, F. P. PITTELLA-SILVA, F.", "title": "Naphthaquinone Methyltransferase Inhibitors and Uses Thereof", "jurisdiction": "Australia (IP Australia)", "number": "AU2015255692", "deposited": "2016-11-03", "url": "https://patents.google.com/?q=AU2015255692"},
    {"year": 2017, "inventors": "LUO, M.; BLUM, G.; SANCHEZ, G. I.; SILVA, F. P. PITTELLA-SILVA, F.", "title": "Naphthaquinone Methyltransferase Inhibitors and Uses Thereof", "jurisdiction": "Japan (JPO)", "number": "JP2017511562", "deposited": "2017-06-15", "url": "https://patents.google.com/?q=JP2017511562"},
    {"year": 2016, "inventors": "LUO, M.; WANG, J.; SILVA, F. P. PITTELLA-SILVA, F.", "title": "SET8 INHIBITORS AND USES THEREOF", "jurisdiction": "USA (USPTO)", "number": "US 62/287,263 (provisional)", "deposited": "2016-01-26", "url": "https://patents.google.com/?q=62%2F287%2C263+SET8+inhibitors"},
]

# ─── PARTNERS ───────────────────────────────────────────────────────────────

PARTNERS = [
    {"name": "Cancer Institute of the State of São Paulo (ICESP)",
     "website": "https://icesp.org.br/cto/", "logo": "partners/icesp.jpg",
     "country": "Brazil",
     "summary": "Translational oncology hub with advanced core facilities, biobank and research groups"},
    {"name": "Green Nanotechnology Laboratory (NaVe)",
     "website": "https://nanotecnologiaverde.complexonano.com/sobre-nos/", "logo": "partners/nave.jpg",
     "country": "UnB – Brazil",
     "summary": "Multi-user lab focused on nanomaterials and nanosystems for health and environment"},
    {"name": "i.rad.Particles",
     "website": "https://i-rad-particles.com/#home", "logo": "partners/rdp.jpg",
     "country": "Brazil",
     "summary": "Deep-tech company in energy and medical biotech; nanoparticle diagnostics and therapies"},
    {"name": "Laboratory for the Development of Nanostructured Systems (LDNano)",
     "website": "https://www2.ufjf.br/ldnano/", "logo": "partners/ldnano.jpg",
     "country": "UFJF – Brazil",
     "summary": "Nanotechnology-based drug delivery to tune pharmacological properties"},
    {"name": "Biometals Lab – Metal Biochemistry, Chemical Biology & Oxidative Stress",
     "website": "https://pnipe.mcti.gov.br/laboratory/23798", "logo": "partners/biom.jpg",
     "country": "UFABC – Brazil",
     "summary": "Biochemistry and bioinorganic chemistry of trace metals in biology"},
    {"name": "Jan Grimm Lab",
     "website": "https://www.mskcc.org/research/ski/labs/jan-grimm", "logo": "partners/msk.jpg",
     "country": "MSKCC – United States",
     "summary": "Imaging-driven nanomedicine for cancer: nanoparticles for therapy, Cerenkov/optoacoustic imaging, and PSMA biology"},
    {"name": "Children's Hospital of Brasília José Alencar",
     "website": "https://www.hcb.org.br/", "logo": "partners/hcb.jpg",
     "country": "Brazil",
     "summary": "Public pediatric hospital providing medium- and high-complexity care, integrating oncology, transplants, teaching, and research"},
    {"name": "Center for Molecular Biotechnology (C-BIOTECH)",
     "website": "https://cbiotech.unb.br/", "logo": "partners/cbio.jpg",
     "country": "UnB - Brazil",
     "summary": "The Center provides shared labs for startups and applies molecular biology to develop biopharmaceuticals, chemicals, biofuels, industrial enzymes, and biomaterials"},
]

FUNDING_LINKS = {
    "cnpq.jpg": "https://www.gov.br/cnpq/pt-br",
    "fapdf.jpg": "https://www.fap.df.gov.br/",
    "decit.jpg": "https://www.gov.br/saude/pt-br/composicao/sectics/decit",
    "capes.svg": "https://www.gov.br/capes/pt-br",
}

# ─── NEWS ───────────────────────────────────────────────────────────────────

NEWS_ITEMS = [
    {"kind": "press",
     "url": "https://www.fap.df.gov.br/w/cancer-de-mama-pesquisa-da-unb-investiga-novos-caminhos-para-conter-a-metastase",
     "date_iso": "2025-10-02",
     "title": "Câncer de mama: pesquisa da UnB investiga novos caminhos para conter a metástase",
     "dek": "FAP-DF feature about CancerLab/UnB research on strategies to contain breast cancer metastasis.",
     "thumb": None},
    {"kind": "video",
     "url": "https://www.youtube.com/watch?v=xiiLgiTCiZM",
     "date_iso": "2025-10-09",
     "title": "Pink October | Globo TV Interview",
     "dek": "Our team discusses ongoing breast cancer research in a special Globo TV interview"},
    {"kind": "press",
     "url": "https://noticias.unb.br/artigos-main/8116-outubro-rosa-o-elo-entre-pesquisa-sociedade-e-a-luta-contra-o-cancer-de-mama",
     "date_iso": "2025-10-17",
     "title": "Outubro Rosa: o elo entre pesquisa, sociedade e a luta contra o câncer de mama",
     "dek": "Nossos pesquisadores investigam novas estratégias para frear o câncer de mama e fortalecer a conscientização",
     "thumb": None},
]

# ─── EQUIPMENT ──────────────────────────────────────────────────────────────

SCHEDULABLE_EQUIPMENT = [
    "qPCR StepOne Plus",
    "TapeStation",
    "Ion S5 Sequencer",
    "Cell Sorter",
    "DNA Workstation",
]
