# Generated by Django 5.1.15 on 2026-07-04 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(db_column='CPF', max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(db_column='nome', max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(db_column='email', max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(db_column='senha', max_length=255, verbose_name='Senha')),
                ('perfil', models.CharField(choices=[('aluno', 'Aluno'), ('servidor', 'Servidor'), ('admin', 'Admin')], db_column='perfil', default='aluno', max_length=30, verbose_name='Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário Interno',
                'verbose_name_plural': 'Usuários Internos',
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('used', models.IntegerField(db_column='used', default=0)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Reset de Senha',
                'db_table': 'password_reset_tokens',
                'managed': True,
            },
        ),
    ]
