# Generated by Django 5.1.15 on 2026-07-04 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=200, verbose_name='Nome do usuário')),
                ('user_email', models.EmailField(db_column='user_email', max_length=254, verbose_name='E-mail do usuário')),
                ('user_phone', models.CharField(db_column='user_phone', max_length=50, verbose_name='Telefone')),
                ('user_fub', models.CharField(db_column='user_fub', max_length=50, verbose_name='Matrícula FUB')),
                ('equipment_name', models.CharField(db_column='equipment_name', max_length=120, verbose_name='Equipamento')),
                ('booking_date', models.CharField(db_column='booking_date', max_length=20, verbose_name='Data')),
                ('booking_time', models.CharField(db_column='booking_time', max_length=10, verbose_name='Horário')),
                ('status', models.CharField(db_column='status', default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, db_column='notes', null=True, verbose_name='Observações')),
                ('reviewed_by', models.CharField(blank=True, db_column='reviewed_by', max_length=200, null=True, verbose_name='Revisado por')),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True, verbose_name='Data da revisão')),
                ('review_note', models.TextField(blank=True, db_column='review_note', null=True, verbose_name='Nota da revisão')),
                ('cancelled_by', models.CharField(blank=True, db_column='cancelled_by', max_length=200, null=True, verbose_name='Cancelado por')),
                ('cancelled_at', models.DateTimeField(blank=True, db_column='cancelled_at', null=True, verbose_name='Data do cancelamento')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Reserva de Equipamento',
                'verbose_name_plural': 'Reservas de Equipamentos',
                'db_table': 'equipment_bookings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_column='full_name', max_length=200, verbose_name='Nome completo')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='E-mail')),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255, verbose_name='Senha (bcrypt)')),
                ('phone', models.CharField(db_column='phone', max_length=50, verbose_name='Telefone')),
                ('fub_registration', models.CharField(db_column='fub_registration', max_length=50, verbose_name='Matrícula FUB')),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Usuário Externo',
                'verbose_name_plural': 'Usuários Externos',
                'db_table': 'external_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_column='action', max_length=30)),
                ('performed_by', models.CharField(db_column='performed_by', max_length=200)),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='bookings.equipmentbooking')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'booking_audit_log',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='external_user',
            field=models.ForeignKey(db_column='external_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='bookings.externaluser'),
        ),
    ]
